---
title: "The 52-weeek High and Momentum Investing: A Partial Replication of George and Hwang (2004)"
author: "Wenhao Yu and Olena Ostasheva"
date: "`May 9th, 2016`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ws.data)
library(lubridate)
library(dplyr)
library(tibble)
library(tidyr)
library(ggplot2)
library(RcppRoll)
data(secref)
data(yearly)
```


#Introduction and Literature Overview

        Considerable research has been conducted to discover predictable patterns in stock behavior.  In contrast with the random walk hypothesis, results generated by Jegadeesh and Titman (1993), Moskowitz and Grinblatt (1999), and George and Hwang (2004) demonstrate that stock returns exhibit momentum behaviors.  Jegadeesh and Titman (1993) developed a strategy for individual stocks based on past returns.  In contrast, Moskowitz and Grinblatt (1999) argued that stock returns are more likely driven by industry momentum than individual stock momentum alone.  George and Hwang (2004) conducted a head to head comparison of the two previous methods, as well as a third strategy based on the relative nearness to a stock’s 52-week high prices.  Their results show that nearness to the 52 week high is a better predictor than past returns.
        Jegadeesh and Titman (1993)’s methodology measures the past 6 months return performance of individual stocks and develops a long portfolio of the 30% percent stocks with the highest return and a short portfolio on the bottom 30% of stocks.  This strategy results in significantly profitable returns, but the authors also determine that the profitability is not due to either systematic risk or to delayed stock price reactions.  These results present a challenge to the view that markets are semistrong-form efficient, that implies that all public information is incorporated into a stock's current share price.
        The second strategy that GH replicate follows similar style of momentum investing but focuses on industries.  Moskowitz and Grinblatt (1999) form a portfolio that takes a long position in 30% of top performing industries and shorts the bottom 30%, with results showing greater profitability compared to individual stock selection.  The results support industries as a significant source of momentum.
        A third method by George and Hwang (2004) is based on relative distance from a stock’s 52 week high price. The ranking of stocks is based on the ratio between a stock’s current prices to its 52 week high price, with portfolio that goes long (short) the highest (lowest) 30% of these ratios.  The rationale for this model is that when stock’s price is near its 52-week high, traders are more reluctant to bid higher despite positive news. The price levels will eventually adjust, but the period of reluctance creates an opportunity for predictability in stock pricing.   Additionally, many economic studies on this phenomenon, such as the “adjustment and anchoring bias” surveyed in Kahneman, Slovic, and Tversky (1982) suggest that traders use 52-week high prices as an “anchor” to which prices will move proportionally.  A comparison conducted in this study shows that although returns are similar in numbers, a large part of individual stock momentum is attributable to stocks with prices either very near or far from the 52-week high.  This explanation indicates a significant influence in the 52-week ratios to the pricing and profitability of individual stocks.


#Replication 
